@WebApi_HostAddress = http://localhost:7033

GET {{WebApi_HostAddress}}/
Accept: application/json

###

PATCH {{WebApi_HostAddress}}/api/v1/admin/quizzes/1
Content-Type: application/json-patch+json

[{
  "op": "add",
  "path": "/items/-",
  "value": {
    "question": "4*7",
    "correctAnswer": "28",
    "incorrectAnswers": ["27", "28", "29"]
  }
}]